### ISSUE TITLE
End of Central Directory record could not be found.

### ISSUE THREAD

**Issue by Hardik-G1** [kitric/comicpeeps#2]
[20:07]: Adding comic: Finish
[20:07]: Generating cover for D:\softwares\Maya2017\Manga\Dream.cbz
[20:07]: End of Central Directory record could not be found.

**Comment by crxssed7** [comment]
Hi @Hardik-G1 
After a quick google search it looks like this error occurs when the file is corrupt... is it possible you could send me over that CBZ file and I'll investigate further? Or you could try uncompressing the file as a zip archive and see if its corrupted that way?

**Comment by Hardik-G1** [comment]
the file is not corrupt the file is working with other cbz readers
